# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditaciones',
            fields=[
                ('id_acreditacion', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'acreditaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnomaliaIrreparable',
            fields=[
                ('id_anom_irr', models.BigIntegerField(primary_key=True, serialize=False)),
                ('terreno', models.CharField(max_length=2)),
                ('plagas', models.CharField(max_length=2)),
                ('fundaciones', models.CharField(max_length=2)),
                ('muros', models.CharField(max_length=2)),
                ('entrepiso', models.CharField(max_length=2)),
                ('estruc_techum', models.CharField(max_length=2)),
                ('red_ag_pot', models.CharField(max_length=2)),
                ('raguas_serv', models.CharField(max_length=2)),
                ('red_electric', models.CharField(max_length=2)),
                ('red_gas', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'anomalia_irreparable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnomaliaReparable',
            fields=[
                ('id_anom_rep', models.BigIntegerField(primary_key=True, serialize=False)),
                ('humedad', models.CharField(max_length=2)),
                ('radier', models.CharField(max_length=2)),
                ('tabiques', models.BigIntegerField()),
                ('revestim_ext', models.CharField(max_length=2)),
                ('revestim_int', models.CharField(max_length=2)),
                ('puertas_ventanas', models.CharField(max_length=2)),
                ('cubierta_tech', models.CharField(max_length=2)),
                ('aap_ags', models.CharField(max_length=2)),
                ('artefactos_elec', models.CharField(max_length=2)),
                ('observaciones', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'anomalia_reparable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecAdminViv',
            fields=[
                ('id_ant_adm', models.BigIntegerField(primary_key=True, serialize=False)),
                ('per_ed_nro', models.BigIntegerField()),
                ('fecha_ed', models.DateField()),
                ('m2', models.BigIntegerField()),
                ('annio_constr', models.BigIntegerField()),
                ('recep_final', models.BigIntegerField()),
                ('fecha_recepc', models.DateField()),
            ],
            options={
                'db_table': 'antec_admin_viv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecConstrViv',
            fields=[
                ('id_antec_constr', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_vivienda', models.CharField(max_length=15)),
                ('num_pisos', models.BigIntegerField()),
                ('agrupacion_viv', models.CharField(max_length=50)),
                ('estar', models.CharField(blank=True, max_length=2, null=True)),
                ('comedor', models.CharField(blank=True, max_length=2, null=True)),
                ('cocina', models.CharField(blank=True, max_length=2, null=True)),
                ('loggia', models.CharField(blank=True, max_length=2, null=True)),
                ('balcon_terraza', models.CharField(blank=True, max_length=2, null=True)),
                ('nro_dormitorios', models.BigIntegerField()),
                ('nro_bannios', models.BigIntegerField()),
                ('estacionamiento', models.CharField(blank=True, max_length=2, null=True)),
                ('bodega', models.CharField(blank=True, max_length=2, null=True)),
                ('otro_recinto', models.CharField(blank=True, max_length=2, null=True)),
                ('superf_viv', models.BigIntegerField()),
                ('superf_terr', models.BigIntegerField()),
            ],
            options={
                'db_table': 'antec_constr_viv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionVivienda',
            fields=[
                ('id_asig_viv', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asignacion_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaVivienda',
            fields=[
                ('id_caract_viv', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usada', models.CharField(max_length=2)),
                ('economica', models.CharField(max_length=2)),
                ('num_depto', models.BigIntegerField(blank=True, null=True)),
                ('num_piso', models.BigIntegerField(blank=True, null=True)),
                ('rol_sii', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_lugar', models.CharField(max_length=40)),
                ('comuna', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'caracteristica_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargaFamiliar',
            fields=[
                ('cedula_identidad', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('relacion_postulante', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'carga_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificadoPermanencia',
            fields=[
                ('id_certificado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tiene_certificado', models.CharField(max_length=2)),
                ('fecha_certificado', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certificado_permanencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id_consultor', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_cons', models.CharField(max_length=20)),
                ('correo_cons', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=40)),
                ('resolucion', models.BigIntegerField()),
                ('fecha_res', models.DateField()),
                ('telefono', models.BigIntegerField()),
            ],
            options={
                'db_table': 'consultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('telefono_movil', models.BigIntegerField()),
                ('telefono_trabajo', models.BigIntegerField(blank=True, null=True)),
                ('telefono_domicilio', models.BigIntegerField(blank=True, null=True)),
                ('codigo_postal', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conyugente',
            fields=[
                ('id_conyugente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=30)),
                ('ap_mat', models.CharField(max_length=30)),
                ('fec_nac', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conyugente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaAhorro',
            fields=[
                ('id_cuenta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.BigIntegerField()),
                ('tipo_cuenta', models.CharField(max_length=45)),
                ('fech_apertura', models.DateField()),
                ('rut_titular', models.CharField(max_length=30)),
                ('desc_titular', models.CharField(max_length=40)),
                ('monto_ahorrado', models.BigIntegerField()),
                ('ent_financiera', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'cuenta_ahorro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocCargaFamiliar',
            fields=[
                ('id_doc_carga', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tiene_carga', models.CharField(max_length=2)),
                ('tiene_acreditacion', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_carga_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocEtnia',
            fields=[
                ('id_doc_etnia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('es_indigena', models.CharField(max_length=2)),
                ('tiene_acreditacion', models.CharField(blank=True, max_length=2, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_etnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocTitulo',
            fields=[
                ('id_doc_titulo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tiene_acreditacion', models.CharField(blank=True, max_length=2, null=True)),
                ('posee_titulo', models.CharField(max_length=2)),
                ('institucion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc_titulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DomicilioPostulante',
            fields=[
                ('id_domicilio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('block', models.BigIntegerField(blank=True, null=True)),
                ('departamento', models.BigIntegerField(blank=True, null=True)),
                ('manzana', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('poblacion_villa', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'domicilio_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErroresProcAsigPuntaje',
            fields=[
                ('id_error', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_subprograma', models.CharField(max_length=100)),
                ('mensaje_error', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'errores_proc_asig_puntaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVivienda',
            fields=[
                ('id_estado_viv', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'estado_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id_etnia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'etnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('num_folio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('nomb_receptor', models.CharField(max_length=50)),
                ('comuna_preferencia', models.CharField(max_length=50)),
                ('region_preferencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformacionPostulante',
            fields=[
                ('nro_folio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('fecha_postulacion', models.DateField()),
                ('receptor_postulacion', models.CharField(max_length=100)),
                ('cedula_postulante', models.CharField(max_length=20)),
                ('fecha_nac_post', models.DateField()),
                ('nom_completo_post', models.CharField(max_length=40)),
                ('nacionalidad_post', models.CharField(max_length=20)),
                ('estado_civil_post', models.CharField(max_length=20)),
                ('total_cargas', models.BigIntegerField()),
                ('pueblo_indigena_post', models.CharField(max_length=2)),
                ('descr_titulo_post', models.CharField(max_length=50)),
                ('numero', models.BigIntegerField()),
                ('calle_post', models.CharField(max_length=100)),
                ('block_post', models.BigIntegerField(blank=True, null=True)),
                ('departamento_post', models.BigIntegerField(blank=True, null=True)),
                ('manzana_post', models.CharField(blank=True, max_length=60, null=True)),
                ('sitio_post', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=70)),
                ('telef_trabajo_post', models.BigIntegerField(blank=True, null=True)),
                ('telef_domicilio_post', models.BigIntegerField(blank=True, null=True)),
                ('telef_movil_post', models.BigIntegerField()),
                ('cod_postal_post', models.BigIntegerField()),
                ('email_post', models.CharField(max_length=100)),
                ('cedula_conyuge', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=100, null=True)),
                ('tramo_postulacion', models.CharField(max_length=40)),
                ('tipo_vivienda', models.CharField(max_length=30)),
                ('valor_propiedad', models.BigIntegerField()),
                ('comuna_viv', models.CharField(max_length=30)),
                ('region_viv', models.CharField(max_length=30)),
                ('monto_ahorrado', models.BigIntegerField()),
                ('puntaje_minimo', models.BigIntegerField()),
                ('puntaje_obtenido', models.BigIntegerField()),
            ],
            options={
                'db_table': 'informacion_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InformeTecnico',
            fields=[
                ('nro_folio_inf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_inspeccion', models.DateField()),
            ],
            options={
                'db_table': 'informe_tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialPredominante',
            fields=[
                ('id_material_pred', models.BigIntegerField(primary_key=True, serialize=False)),
                ('techumbre', models.CharField(max_length=200)),
                ('muros', models.CharField(max_length=200)),
                ('pisos_entrepisos', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'material_predominante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id_postulacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nro_folio', models.BigIntegerField()),
                ('rut_postulante', models.CharField(max_length=20)),
                ('fecha_postulacion', models.DateField()),
                ('mes_valido', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_post', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('ap_pat', models.CharField(max_length=30)),
                ('ap_mat', models.CharField(max_length=30)),
                ('fec_nac', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('separado_acreditado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_prop', models.CharField(max_length=20)),
                ('nom_propi', models.CharField(max_length=50)),
                ('correo_elect', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
            ],
            options={
                'db_table': 'propietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajeEstadoCivil',
            fields=[
                ('id_pje_estad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('puntaje', models.BigIntegerField()),
            ],
            options={
                'db_table': 'puntaje_estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajeEtnia',
            fields=[
                ('id_pje_etnia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pertenece_etnia', models.CharField(max_length=2)),
                ('puntaje', models.BigIntegerField()),
            ],
            options={
                'db_table': 'puntaje_etnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajePostulante',
            fields=[
                ('rut_postulante', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('edad', models.BigIntegerField()),
                ('puntaje_edad', models.BigIntegerField()),
                ('cargas_familiares', models.BigIntegerField()),
                ('puntaje_cargas_familiares', models.BigIntegerField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('puntaje_estado_ivil', models.BigIntegerField()),
                ('pueblo_ind_orig', models.CharField(max_length=30)),
                ('puntaje_pueblo_ind_orig', models.BigIntegerField()),
                ('monto_ahorro', models.BigIntegerField()),
                ('puntaje_monto_ahorro', models.BigIntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('puntaje_titulo', models.BigIntegerField()),
                ('puntaje_total', models.BigIntegerField()),
            ],
            options={
                'db_table': 'puntaje_postulante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntajeTitulo',
            fields=[
                ('id_rango_titulo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('pje_titulo_p', models.BigIntegerField()),
            ],
            options={
                'db_table': 'puntaje_titulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoPuntajeCarga',
            fields=[
                ('id_rango_carga', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valor_ini', models.BigIntegerField()),
                ('valor_fin', models.BigIntegerField()),
                ('puntaje_carga', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rango_puntaje_carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoPuntajeEdad',
            fields=[
                ('id_rango_edad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valor_ini', models.BigIntegerField()),
                ('valor_fin', models.BigIntegerField()),
                ('puntaje_edad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rango_puntaje_edad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoPuntajeMonto',
            fields=[
                ('id_rango_monto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('valor_ini', models.BigIntegerField()),
                ('valor_fin', models.BigIntegerField()),
                ('pje_monto_ahorrado', models.BigIntegerField()),
            ],
            options={
                'db_table': 'rango_puntaje_monto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionesExtremas',
            fields=[
                ('id_reg_extr', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('porcentaje', models.BigIntegerField()),
            ],
            options={
                'db_table': 'regiones_extremas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id_tramo_sub', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subsidio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id_titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'titulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id_tramo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('valor_hasta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tramo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionVivienda',
            fields=[
                ('id_ubicacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comuna_preferencia', models.CharField(max_length=30)),
                ('valor_vivienda', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ubicacion_vivienda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_viv', models.BigIntegerField(primary_key=True, serialize=False)),
                ('conclusion', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'vivienda',
                'managed': False,
            },
        ),
    ]
